local PLUGIN = PLUGIN
PLUGIN.name = "ExtraHL2RP Voices"
PLUGIN.description = 'Adds extra voices for Citizens and OTA'

-- Female voices are practically just a copy of the male voices.
-- There may be a few that don't work because there is no female equivalent to the male Voices
-- Some voices are from Episode 1 so you will need the content in your addons folder of your server so all clients can hear It
-- Or subscribe to the addon I have on the workshop or have the game installed and mounted for it to be audible

-- You can find my upload of Episode 1 male voices here.
--https://steamcommunity.com/sharedfiles/filedetails/?id=3164508401

Schema.voices.Add("CitizenMale", "Hurt1", "*Hhah, -tsch!*", "vo/episode_1/npc/male01/cit_pain01.wav")
Schema.voices.Add("CitizenMale", "Hurt2", "*Gyhoh!*", "vo/episode_1/npc/male01/cit_pain02.wav")
Schema.voices.Add("CitizenMale", "Hurt3", "*Ghaeugh...*", "vo/episode_1/npc/male01/cit_pain03.wav")
Schema.voices.Add("CitizenMale", "Hurt4", "*Gaah-*", "vo/episode_1/npc/male01/cit_pain05.wav")
Schema.voices.Add("CitizenMale", "Ow", "*-Ow*", "vo/episode_1/npc/male01/cit_pain12.wav")
Schema.voices.Add("CitizenMale", "Hahaha", "Hahahaha!", "vo/episode_1/npc/male01/cit_kill20.wav")
Schema.voices.Add("CitizenMale", "Hi", "Hi.", "vo/npc/male01/hi01.wav")
Schema.voices.Add("CitizenMale", "Hi2", "Hi.", "vo/npc/male01/hi02.wav")
Schema.voices.Add("CitizenMale", "Doc", "Hey, Doc.", "vo/npc/male01/heydoc01.wav")
Schema.voices.Add("CitizenMale", "Doc2", "Hey, Doc.", "vo/npc/male01/heydoc02.wav")
Schema.voices.Add("CitizenMale", "Ok", "Ok", "vo/npc/male01/ok01.wav")
Schema.voices.Add("CitizenMale", "Okay", "Okay", "vo/npc/male01/ok02.wav")
Schema.voices.Add("CitizenMale", "Oops", "Whoops", "vo/npc/male01/whoops01.wav")
Schema.voices.Add("CitizenMale", "Whoops", "Whoops", "vo/npc/male01/whoops01.wav")
Schema.voices.Add("CitizenMale", "Right on", "Right on", "vo/npc/male01/answer32.wav")
Schema.voices.Add("CitizenMale", "Bet", "Wanna bet?", "vo/npc/male01/answer27.wav")
Schema.voices.Add("CitizenMale", "Same here", "Same here", "vo/npc/male01/answer07.wav")
Schema.voices.Add("CitizenMale", "Finally", "Finally", "vo/npc/male01/finally.wav")
Schema.voices.Add("CitizenMale", "New in town", "New in town, aren't ya?", "vo/trainyard/male01/cit_pedestrian01.wav")
Schema.voices.Add("CitizenMale", "Psst", "*Psst*- Hey you, in here!", "vo/trainyard/cit_hall_psst.wav")
Schema.voices.Add("CitizenMale", "I'm moving", "Alright I'm moving-*geeze*", "vo/trainyard/cit_lug_allright.wav")
Schema.voices.Add("CitizenMale", "It's alright", "It's alright..", "vo/trainyard/husb_allright.wav")
Schema.voices.Add("CitizenMale", "Me?", "*Me?*", "vo/trainyard/man_me.wav")
Schema.voices.Add("CitizenMale", "Wait a minute", "Wait a minute-", "vo/trainyard/man_waitaminute.wav")
Schema.voices.Add("CitizenMale", "Taking", "Where're you taking me?", "vo/trainyard/man_whereyoutakingme.wav")
Schema.voices.Add("CitizenMale", "Shit", "Shit!", "vo/outland_12/reb1_buildingexplo06.wav")
Schema.voices.Add("CitizenMale", "Personal", "*Alright*... now it's personal!", "vo/outland_12/reb1_buildingexplo03.wav")
Schema.voices.Add("CitizenMale", "Incoming", "Incooooming!", "vo/outland_12/reb1_lastwave09.wav")
Schema.voices.Add("CitizenMale", "Civil", "Civil Protection!", "vo/npc/male01/civilprotection01.wav")
Schema.voices.Add("CitizenMale", "Civil2", "Civil Protection!", "vo/npc/male01/civilprotection02.wav")
Schema.voices.Add("CitizenMale", "CPs", "CPs!", "vo/npc/male01/cps01.wav")
Schema.voices.Add("CitizenMale", "CPs2", "CPs!", "vo/npc/male01/cps02.wav")
Schema.voices.Add("CitizenMale", "Combine", "Combine!", "vo/npc/male01/combine01.wav")
Schema.voices.Add("CitizenMale", "Combine2", "Combine!", "vo/npc/male01/combine02.wav")
Schema.voices.Add("CitizenMale", "Headcrabs", "Headcrabs!", "vo/npc/male01/headcrabs01.wav")
Schema.voices.Add("CitizenMale", "Headcrabs2", "Headcrabs!", "vo/npc/male01/headcrabs02.wav")
Schema.voices.Add("CitizenMale", "Zombies", "Zombies!", "vo/npc/male01/zombies01.wav")
Schema.voices.Add("CitizenMale", "Zombies2", "Zombies!", "vo/npc/male01/zombies02.wav")
Schema.voices.Add("CitizenMale", "Strider", "Striiiider!", "vo/npc/male01/strider.wav")
Schema.voices.Add("CitizenMale", "Kill it", "Kill it!", "vo/episode_1/npc/male01/cit_alert_zombie09")
Schema.voices.Add("CitizenMale", "Vorts", "Damn Vorts.", "vo/npc/male01/vanswer02.wav")
Schema.voices.Add("CitizenMale", "Vorts2", "None of your Vort philosophy...", "vo/npc/male01/vanswer12.wav")
Schema.voices.Add("CitizenMale", "Vorty", "You're alright, Vorty.", "vo/npc/male01/vanswer12.wav")
Schema.voices.Add("CitizenMale", "Arm", "*Gah*- My arm!", "vo/npc/male01/myarm01.wav")
Schema.voices.Add("CitizenMale", "Arm2", "*Ghah*- My arm!", "vo/npc/male01/myarm02.wav")
Schema.voices.Add("CitizenMale", "Leg", "*Gah*- My leg!", "vo/npc/male01/myleg01.wav")
Schema.voices.Add("CitizenMale", "Leg2", "*Ghoh*- My leg!", "vo/npc/male01/myleg02.wav")
Schema.voices.Add("CitizenMale", "Gut", "*Ghah-ahh* My gut!", "vo/npc/male01/mygut02.wav")
Schema.voices.Add("CitizenMale", "I'm hurt", "I'm hurt", "vo/npc/male01/imhurt02.wav")
Schema.voices.Add("CitizenMale", "Sick", "*I'm gonna be sick...*", "vo/npc/male01/gordead_ans19.wav")
Schema.voices.Add("CitizenMale", "Don't tell me", "Don't tell me.", "vo/npc/male01/gordead_ans03.wav")
Schema.voices.Add("CitizenMale", "Going", "...Okay, I\'m going.", "vo/npc/male01/squad_affirm04.wav")
Schema.voices.Add("CitizenMale", "Here goes", "Here goes..", "vo/npc/male01/squad_affirm05.wav")
Schema.voices.Add("CitizenMale", "hawaii", "Hawaii", "vo/npc/male01/answer34.wav")
Schema.voices.Add("CitizenMale", "figures", "Figures.", "vo/npc/male01/answer03.wav")
Schema.voices.Add("CitizenMale", "keep your mind", "Keep your mind on your work.", "vo/npc/male01/answer19.wav")
Schema.voices.Add("CitizenMale", "talking to me", "You talkin' to me?", "vo/npc/male01/answer30.wav")
Schema.voices.Add("CitizenMale", "leave it", "Leave it alone....", "vo/npc/male01/answer38.wav")
Schema.voices.Add("CitizenMale", "hold it against", "I won't hold it against you.", "vo/npc/male01/answer02.wav")
Schema.voices.Add("CitizenMale", "oh no", "Oh no.", "vo/npc/male01/ohno.wav")
Schema.voices.Add("CitizenMale", "no no", "No, no!", "vo/npc/male01/no01.wav")
Schema.voices.Add("CitizenMale", "no!", "NO!", "vo/npc/male01/no02.wav")
Schema.voices.Add("CitizenMale", "over here", "Hey, over here!", "vo/npc/male01/overhere01.wav")
Schema.voices.Add("CitizenMale", "lets go", "Let's go!", "vo/npc/male01/letsgo02.wav")
Schema.voices.Add("CitizenMale", "let's go", "Let's go!", "vo/npc/male01/letsgo02.wav")
Schema.voices.Add("CitizenMale", "lets go2", "Let's.. GO!", "vo/npc/male01/letsgo01.wav")
Schema.voices.Add("CitizenMale", "let's go2", "Let's.. GO!", "vo/npc/male01/letsgo01.wav")
Schema.voices.Add("CitizenMale", "im ready", "Okay, I'm ready.", "vo/npc/male01/okimready02.wav")
Schema.voices.Add("CitizenMale", "i'm ready", "Okay, I'm ready.", "vo/npc/male01/okimready02.wav")
Schema.voices.Add("CitizenMale", "one for me", "One for me and one... for me.", "vo/npc/male01/oneforme.wav")
Schema.voices.Add("CitizenMale", "over there", "Over there!", "vo/npc/male01/overthere02.wav")
Schema.voices.Add("CitizenMale", "cheese", "Sometimes.. I dream about cheese...", "vo/npc/male01/question06.wav")
Schema.voices.Add("CitizenMale", "i dont think this war", "I don't think this war's ever gonna end...", "vo/npc/male01/question01.wav")
Schema.voices.Add("CitizenMale", "i don't think this war", "I don't think this war's ever gonna end...", "vo/npc/male01/question01.wav")
Schema.voices.Add("CitizenMale", "insurance", "To think - All I used to wanna do was sell insurance...", "vo/npc/male01/question02.wav")
Schema.voices.Add("CitizenMale", "i dont dream", "I don't dream anymore.", "vo/npc/male01/question03.wav")
Schema.voices.Add("CitizenMale", "i don't dream", "I don't dream anymore.", "vo/npc/male01/question03.wav")
Schema.voices.Add("CitizenMale", "when this is all over", "When this is all over.. Ah who am I kidding?", "vo/npc/male01/question04.wav")
Schema.voices.Add("CitizenMale", "deja vu", "Woah.. déjà vu!", "vo/npc/male01/question05.wav")
Schema.voices.Add("CitizenMale", "you smell that", "You smell that? It's freedom.", "vo/npc/male01/question07.wav")
Schema.voices.Add("CitizenMale", "i could eat a horse", "I could eat a horse - hooves and all.", "vo/npc/male01/question09.wav")
Schema.voices.Add("CitizenMale", "bad memory", "Someday.. this'll all be a bad memory.", "vo/npc/male01/question20.wav")
Schema.voices.Add("CitizenMale", "betting man", "I'm not a betting man but.. the odds are not good.", "vo/npc/male01/question21.wav")
Schema.voices.Add("CitizenMale", "whistle", "I can't get this tune out of my head. *Whistles*", "vo/npc/male01/question23.wav")
Schema.voices.Add("CitizenMale", "this is bullshit", "This is bullshit.", "vo/npc/male01/question26.wav")
Schema.voices.Add("CitizenMale", "mate", "When this is all over... I'm gonna mate.", "vo/npc/male01/question29.wav")
Schema.voices.Add("CitizenMale", "no kids around", "I'm glad there's no kids around to see this.", "vo/npc/male01/question30.wav")
Schema.voices.Add("CitizenMale", "the last time", "I can't remember the last time I had... well.. anything.", "vo/npc/male01/question31.wav")
Schema.voices.Add("CitizenMale", "run for your life", "RUN FOR YOUR LIFE!", "vo/npc/male01/runforyourlife01.wav")
Schema.voices.Add("CitizenMale", "run for your life2", "RUN FOR YOUR LIFE!", "vo/npc/male01/runforyourlife02.wav")
Schema.voices.Add("CitizenMale", "run for your life3", "RUN FOR YOUR LIFE!", "vo/npc/male01/runforyourlife03.wav")
Schema.voices.Add("CitizenMale", "sorry", "Sorry.", "vo/npc/male01/sorry01.wav")
Schema.voices.Add("CitizenMale", "sorry2", "Sorry.", "vo/npc/male01/sorry02.wav")
Schema.voices.Add("CitizenMale", "sorry3", "Sorry.", "vo/npc/male01/sorry03.wav")
Schema.voices.Add("CitizenMale", "follow me", "Follow me!", "vo/npc/male01/squad_away03.wav")
Schema.voices.Add("CitizenMale", "cmon everybody", "C'mon, everybody!", "vo/npc/male01/squad_follow02.wav")
Schema.voices.Add("CitizenMale", "wait for us", "Wait for us!", "vo/npc/male01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenMale", "wait for me", "Wait for me!", "vo/npc/male01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenMale", "run", "RUUUUUN!", "vo/npc/male01/strider_run.wav")
Schema.voices.Add("CitizenMale", "take cover", "Take cover!", "vo/npc/male01/takecover02.wav")
Schema.voices.Add("CitizenMale", "hacks3", "THE HACKS!", "vo/npc/male01/thehacks01.wav")
Schema.voices.Add("CitizenMale", "hacks2", "The hacks!", "vo/npc/male01/thehacks02.wav")
Schema.voices.Add("CitizenMale", "up there", "Up there!", "vo/npc/male01/upthere01.wav")
Schema.voices.Add("CitizenMale", "up there2", "Up there!", "vo/npc/male01/upthere02.wav")
Schema.voices.Add("CitizenMale", "mumbojumbo", "Enough of your mumbojumbo.", "vo/npc/male01/vanswer01.wav")
Schema.voices.Add("CitizenMale", "speak english", "Speak English!", "vo/npc/male01/vanswer05.wav")
Schema.voices.Add("CitizenMale", "used to you", "I guess I'm getting used to you Vorts.", "vo/npc/male01/vanswer11.wav")
Schema.voices.Add("CitizenMale", "youre killing me", "Stop, you're killin' me.", "vo/npc/male01/vanswer13.wav")
Schema.voices.Add("CitizenMale", "looking at me like that", "Would you stop looking at me like that?", "vo/npc/male01/vquestion01.wav")
Schema.voices.Add("CitizenMale", "ended up with you", "Sometimes I wonder how I ended up with you.", "vo/npc/male01/vquestion04.wav")
Schema.voices.Add("CitizenMale", "vorty2", "You're alright, Vorty.", "vo/npc/male01/vquestion05.wav")
Schema.voices.Add("CitizenMale", "half bad", "You Vorts aren't half bad.", "vo/npc/male01/vquestion06.wav")
Schema.voices.Add("CitizenMale", "waiting for somebody", "You waiting for somebody?", "vo/npc/male01/waitingsomebody.wav")
Schema.voices.Add("CitizenMale", "watch out", "Watch out!", "vo/npc/male01/watchout.wav")
Schema.voices.Add("CitizenMale", "yeah", "Yeah!", "vo/npc/male01/yeah02.wav")
Schema.voices.Add("CitizenMale", "cover me", "Cover me while I reload!", "vo/npc/male01/coverwhilereload01.wav")
Schema.voices.Add("CitizenMale", "cover me2", "Cover me while I reload!", "vo/npc/male01/coverwhilereload02.wav")
Schema.voices.Add("CitizenMale", "even the odds", "Let's even the odds a little.", "vo/npc/male01/evenodds.wav")
Schema.voices.Add("CitizenMale", "fantastic", "Fantastic!", "vo/npc/male01/fantastic01.wav")
Schema.voices.Add("CitizenMale", "fantastic2", "Fantastic!", "vo/npc/male01/fantastic02.wav")
Schema.voices.Add("CitizenMale", "get the hell out", "GET THE HELL OUT OF HERE!", "vo/npc/male01/gethellout.wav")
Schema.voices.Add("CitizenMale", "good god", "Good god!", "vo/npc/male01/goodgod.wav")
Schema.voices.Add("CitizenMale", "oh god", "Oh god!", "vo/npc/male01/gordead_ans04.wav")
Schema.voices.Add("CitizenMale", "hes dead", "He's dead.", "vo/npc/male01/gordead_ques01.wav")
Schema.voices.Add("CitizenMale", "look hes dead", "Look! He's dead!", "vo/npc/male01/gordead_ques07.wav")
Schema.voices.Add("CitizenMale", "he's dead", "He's dead.", "vo/npc/male01/gordead_ques01.wav")
Schema.voices.Add("CitizenMale", "look he's dead", "Look! He's dead!", "vo/npc/male01/gordead_ques07.wav")
Schema.voices.Add("CitizenMale", "got one", "Got one!", "vo/npc/male01/gotone01.wav")
Schema.voices.Add("CitizenMale", "got one2", "Haha! I got one!", "vo/npc/male01/gotone02.wav")
Schema.voices.Add("CitizenMale", "hacks", "HACKS!", "vo/npc/male01/hacks01.wav")
Schema.voices.Add("CitizenMale", "medkit", "Take this medkit.", "vo/npc/male01/health01.wav")
Schema.voices.Add("CitizenMale", "medkit2", "Take this medkit!", "vo/npc/male01/health03.wav")
Schema.voices.Add("CitizenMale", "help", "HELP!", "vo/npc/male01/help01.wav")
Schema.voices.Add("CitizenMale", "help!", "HELP!", "vo/npc/male01/help01.wav")
Schema.voices.Add("CitizenMale", "ill stay here", "I'll stay here.", "vo/npc/male01/illstayhere01.wav")
Schema.voices.Add("CitizenMale", "i'll stay here", "I'll stay here.", "vo/npc/male01/illstayhere01.wav")
Schema.voices.Add("CitizenMale", "help2", "Help!", "vo/streetwar/sniper/male01/c17_09_help01.wav")
Schema.voices.Add("CitizenMale", "help3", "Help me!", "vo/streetwar/sniper/male01/c17_09_help02.wav")
Schema.voices.Add("CitizenMale", "woohoo", "Woo hoo! Woo hoo! YES!", "vo/coast/odessa/male01/nlo_cheer01.wav")
Schema.voices.Add("CitizenMale", "woohoo2", "Woohoo!", "vo/coast/odessa/male01/nlo_cheer02.wav")
Schema.voices.Add("CitizenMale", "hahaha2", "Ha Ha! Hahahaha! Yeah!", "vo/coast/odessa/male01/nlo_cheer03.wav")
Schema.voices.Add("CitizenMale", "yeah2", "Yeah! Waaaaaaa!", "vo/coast/odessa/male01/nlo_cheer04.wav")
Schema.voices.Add("CitizenMale", "shit2", "Shit!", "vo/episode_1/npc/male01/cit_alert_head06.wav")
Schema.voices.Add("CitizenMale", "the hell is that", "What the hell is that?", "vo/episode_1/npc/male01/cit_alert_head07.wav")
Schema.voices.Add("CitizenMale", "help4", "Help!", "vo/episode_1/npc/male01/cit_alert_rollers04.wav")
Schema.voices.Add("CitizenMale", "leaders gone", "Their leader's gone why the hell are they sticking around?", "vo/episode_1/npc/male01/cit_alert_soldier03.wav")
Schema.voices.Add("CitizenMale", "the hell is that", "What the hell is that?", "vo/episode_1/npc/male01/cit_alert_zombie03.wav")
Schema.voices.Add("CitizenMale", "kill it", "Kill it.", "vo/episode_1/npc/male01/cit_alert_zombie04.wav")
Schema.voices.Add("CitizenMale", "what in gods name", "What in God's name is that thing?", "vo/episode_1/npc/male01/cit_alert_zombie05.wav")
Schema.voices.Add("CitizenMale", "shoot him", "Shoot him!", "vo/episode_1/npc/male01/cit_alert_zombie06.wav")
Schema.voices.Add("CitizenMale", "aim for the head", "Aim for the head!", "vo/episode_1/npc/male01/cit_alert_zombie07.wav")
Schema.voices.Add("CitizenMale", "i know that guy", "Holy crap, I think I know that guy.", "vo/episode_1/npc/male01/cit_alert_zombie08.wav")
Schema.voices.Add("CitizenMale", "kill it2", "Kill it!", "vo/episode_1/npc/male01/cit_alert_zombie09.wav")
Schema.voices.Add("CitizenMale", "you okay?", "You okay?", "vo/episode_1/npc/male01/cit_buddykilled01.wav")
Schema.voices.Add("CitizenMale", "you okay", "You okay?", "vo/episode_1/npc/male01/cit_buddykilled01.wav")
Schema.voices.Add("CitizenMale", "i'm pissed", "That's it... I'm PISSED!", "vo/episode_1/npc/male01/cit_buddykilled12.wav")
Schema.voices.Add("CitizenMale", "i'm pissed", "That's it... I'm PISSED!", "vo/episode_1/npc/male01/cit_buddykilled12.wav")
Schema.voices.Add("CitizenMale", "killed the new guy", "He killed the new guy!", "vo/episode_1/npc/male01/cit_buddykilled13.wav")
Schema.voices.Add("CitizenMale", "come here", "Come here!", "vo/episode_1/npc/male01/cit_comehere.wav")
Schema.voices.Add("CitizenMale", "that was close", "Oh god that was close.", "vo/episode_1/npc/male01/cit_evac_casualty06.wav")
Schema.voices.Add("CitizenMale", "help5", "HEEEELLLLP!", "vo/episode_1/npc/male01/cit_evac_casualty08.wav")
Schema.voices.Add("CitizenMale", "help6", "Holy crap! HELP!", "vo/episode_1/npc/male01/cit_evac_casualty11.wav")
Schema.voices.Add("CitizenMale", "for the trains", "Make for the trains!", "vo/episode_1/npc/male01/cit_evac_defendus07.wav")
Schema.voices.Add("CitizenMale", "see those trains", "Never thought I'd be happy to see those trains again.", "vo/episode_1/npc/male01/cit_evac_defendus08.wav")
Schema.voices.Add("CitizenMale", "they're coming", "They're coming!", "vo/episode_1/npc/male01/cit_evac_enemies01.wav")
Schema.voices.Add("CitizenMale", "ask me twice", "You don't gotta ask me twice. Let's go.", "vo/episode_1/npc/male01/cit_evac_ok04.wav")
Schema.voices.Add("CitizenMale", "never make it", "I thought we'd never make it.", "vo/episode_1/npc/male01/cit_evac_thanks04.wav")
Schema.voices.Add("CitizenMale", "haul ass", "Haul ass!", "vo/episode_1/npc/male01/cit_getaboard03.wav")
Schema.voices.Add("CitizenMale", "get in quick", "Get in quick!", "vo/episode_1/npc/male01/cit_getaboard05.wav")
Schema.voices.Add("CitizenMale", "hey over here", "Hey, over here!", "vo/episode_1/npc/male01/cit_heyoverhere.wav")
Schema.voices.Add("CitizenMale", "yeah3", "Yeah..", "vo/episode_1/npc/male01/cit_kill11.wav")
Schema.voices.Add("CitizenMale", "mate now", "Dr. Kleiner says that we can mate now. Not that I needed his permission...", "vo/episode_1/npc/male01/cit_remarks08.wav")
Schema.voices.Add("CitizenMale", "baby striders", "I hear they put babies in those striders.", "vo/episode_1/npc/male01/cit_remarks10.wav")
Schema.voices.Add("CitizenMale", "dont trust vorts", "Between you and me, I don't trust those Vortigaunts.", "vo/episode_1/npc/male01/cit_remarks17.wav")
Schema.voices.Add("CitizenMale", "combine not easy", "The combine's not makin' it easy. We're trying to get enough people together to force our way through to the train station. People are meeting up in a safehouse nearby.", "vo/episode_1/npc/male01/cit_safehouse.wav")
Schema.voices.Add("CitizenMale", "reload", "Cover me while I reload.", "vo/npc/male01/coverwhilereload01.wav")
Schema.voices.Add("CitizenMale", "reload2", "Cover me while I reload!", "vo/npc/male01/coverwhilereload02.wav")


-- Female voices by 4illNation:
Schema.voices.Add("CitizenFemale", "zombies", "Zombies!", "vo/npc/female01/zombies01.wav")
Schema.voices.Add("CitizenFemale", "zombies2", "Zombies!", "vo/npc/female01/zombies02.wav")
Schema.voices.Add("CitizenFemale", "reload", "Cover me while I reload.", "vo/npc/female01/coverwhilereload01.wav")
Schema.voices.Add("CitizenFemale", "reload2", "Cover me while I reload!", "vo/npc/female01/coverwhilereload02.wav")
Schema.voices.Add("CitizenFemale", "oh no", "Oh no.", "vo/npc/female01/ohno.wav")
Schema.voices.Add("CitizenFemale", "Hahaha", "Hahahaha!", "vo/episode_1/npc/female01/cit_kill20.wav")
Schema.voices.Add("CitizenFemale", "no", "No!", "vo/npc/female01/no01.wav")
Schema.voices.Add("CitizenFemale", "no!", "NO!", "vo/npc/female01/no02.wav")
Schema.voices.Add("CitizenFemale", "over here", "Hey, over here!", "vo/npc/female01/overhere01.wav")
Schema.voices.Add("CitizenFemale", "lets go", "Let's go!", "vo/npc/female01/letsgo02.wav")
Schema.voices.Add("CitizenFemale", "let's go", "Let's go!", "vo/npc/female01/letsgo02.wav")
Schema.voices.Add("CitizenFemale", "lets go2", "Let's go!", "vo/npc/female01/letsgo01.wav")
Schema.voices.Add("CitizenFemale", "let's go2", "Let's.. GO!", "vo/npc/female01/letsgo01.wav")
Schema.voices.Add("CitizenFemale", "im ready", "Okay, I'm ready.", "vo/npc/female01/okimready02.wav")
Schema.voices.Add("CitizenFemale", "i'm ready", "Okay, I'm ready.", "vo/npc/female01/okimready02.wav")
Schema.voices.Add("CitizenFemale", "one for me", "One for me and one... for me.", "vo/npc/female01/oneforme.wav")
Schema.voices.Add("CitizenFemale", "over there", "Over there!", "vo/npc/female01/overthere02.wav")
Schema.voices.Add("CitizenFemale", "cheese", "Sometimes.. I dream about cheese...", "vo/npc/female01/question06.wav")
Schema.voices.Add("CitizenFemale", "i dont think this war", "I don't think this war's ever gonna end...", "vo/npc/female01/question01.wav")
Schema.voices.Add("CitizenFemale", "i don't think this war", "I don't think this war's ever gonna end...", "vo/npc/female01/question01.wav")
Schema.voices.Add("CitizenFemale", "insurance", "To think - All I used to wanna do was sell insurance...", "vo/npc/female01/question02.wav")
Schema.voices.Add("CitizenFemale", "i dont dream", "I don't dream anymore.", "vo/npc/female01/question03.wav")
Schema.voices.Add("CitizenFemale", "i don't dream", "I don't dream anymore.", "vo/npc/female01/question03.wav")
Schema.voices.Add("CitizenFemale", "when this is all over", "When this is all over.. Ah who am I kidding?", "vo/npc/female01/question04.wav")
Schema.voices.Add("CitizenFemale", "deja vu", "Woah.. déjà vu!", "vo/npc/female01/question05.wav")
Schema.voices.Add("CitizenFemale", "you smell that", "You smell that? It's freedom.", "vo/npc/female01/question07.wav")
Schema.voices.Add("CitizenFemale", "i could eat a horse", "I could eat a horse - hooves and all.", "vo/npc/female01/question09.wav")
Schema.voices.Add("CitizenFemale", "bad memory", "Someday.. this'll all be a bad memory.", "vo/npc/female01/question20.wav")
Schema.voices.Add("CitizenFemale", "betting man", "I'm not a betting man but.. the odds are not good.", "vo/npc/female01/question21.wav")
Schema.voices.Add("CitizenFemale", "whistle", "I can't get this tune out of my head. *Whistles*", "vo/npc/female01/question23.wav")
Schema.voices.Add("CitizenFemale", "this is bullshit", "This is bullshit.", "vo/npc/female01/question26.wav")
Schema.voices.Add("CitizenFemale", "mate", "When this is all over... I'm gonna mate.", "vo/npc/female01/question29.wav")
Schema.voices.Add("CitizenFemale", "no kids around", "I'm glad there's no kids around to see this.", "vo/npc/female01/question30.wav")
Schema.voices.Add("CitizenFemale", "the last time", "I can't remember the last time I had... well.. anything.", "vo/npc/female01/question31.wav")
Schema.voices.Add("CitizenFemale", "run for your life", "RUN FOR YOUR LIFE!", "vo/npc/female01/runforyourlife01.wav")
Schema.voices.Add("CitizenFemale", "run for your life2", "RUN FOR YOUR LIFE!", "vo/npc/female01/runforyourlife02.wav")
Schema.voices.Add("CitizenFemale", "run for your life3", "RUN FOR YOUR LIFE!", "vo/npc/female01/runforyourlife03.wav")
Schema.voices.Add("CitizenFemale", "sorry", "Sorry.", "vo/npc/female01/sorry01.wav")
Schema.voices.Add("CitizenFemale", "sorry2", "Sorry.", "vo/npc/female01/sorry02.wav")
Schema.voices.Add("CitizenFemale", "sorry3", "Sorry.", "vo/npc/female01/sorry03.wav")
Schema.voices.Add("CitizenFemale", "follow me", "Follow me!", "vo/npc/female01/squad_away03.wav")
Schema.voices.Add("CitizenFemale", "cmon everybody", "C'mon, everybody!", "vo/npc/female01/squad_follow02.wav")
Schema.voices.Add("CitizenFemale", "wait for us", "Wait for us!", "vo/npc/female01/squad_reinforce_group04.wav")
Schema.voices.Add("CitizenFemale", "wait for me", "Wait for me!", "vo/npc/female01/squad_reinforce_single04.wav")
Schema.voices.Add("CitizenFemale", "run", "RUUUUUN!", "vo/npc/female01/strider_run.wav")
Schema.voices.Add("CitizenFemale", "take cover", "Take cover!", "vo/npc/female01/takecover02.wav")
Schema.voices.Add("CitizenFemale", "hacks3", "THE HACKS!", "vo/npc/female01/thehacks01.wav")
Schema.voices.Add("CitizenFemale", "hacks2", "The hacks!", "vo/npc/female01/thehacks02.wav")
Schema.voices.Add("CitizenFemale", "up there", "Up there!", "vo/npc/female01/upthere01.wav")
Schema.voices.Add("CitizenFemale", "up there2", "Up there!", "vo/npc/female01/upthere02.wav")
Schema.voices.Add("CitizenFemale", "mumbo", "Enough of your mumbojumbo.", "vo/npc/female01/vanswer01.wav")
Schema.voices.Add("CitizenFemale", "speak english", "Speak English!", "vo/npc/female01/vanswer05.wav")
Schema.voices.Add("CitizenFemale", "used to you", "I guess I'm getting used to you Vorts.", "vo/npc/female01/vanswer11.wav")
Schema.voices.Add("CitizenFemale", "youre killing me", "Stop, you're killin' me.", "vo/npc/female01/vanswer13.wav")
Schema.voices.Add("CitizenFemale", "looking at me like that", "Would you stop looking at me like that?", "vo/npc/female01/vquestion01.wav")
Schema.voices.Add("CitizenFemale", "ended up with you", "Sometimes I wonder how I ended up with you.", "vo/npc/female01/vquestion04.wav")
Schema.voices.Add("CitizenFemale", "vorty2", "You're alright, Vorty.", "vo/npc/female01/vquestion05.wav")
Schema.voices.Add("CitizenFemale", "half bad", "You Vorts aren't half bad.", "vo/npc/female01/vquestion06.wav")
Schema.voices.Add("CitizenFemale", "waiting for somebody", "You waiting for somebody?", "vo/npc/female01/waitingsomebody.wav")
Schema.voices.Add("CitizenFemale", "watch out", "Watch out!", "vo/npc/female01/watchout.wav")
Schema.voices.Add("CitizenFemale", "yeah", "Yeah!", "vo/npc/female01/yeah02.wav")
Schema.voices.Add("CitizenFemale", "cover me", "Cover me while I reload!", "vo/npc/female01/coverwhilereload01.wav")
Schema.voices.Add("CitizenFemale", "cover me2", "Cover me while I reload!", "vo/npc/female01/coverwhilereload02.wav")
Schema.voices.Add("CitizenFemale", "even the odds", "Let's even the odds a little.", "vo/npc/female01/evenodds.wav")
Schema.voices.Add("CitizenFemale", "fantastic", "Fantastic!", "vo/npc/female01/fantastic01.wav")
Schema.voices.Add("CitizenFemale", "fantastic2", "Fantastic!", "vo/npc/female01/fantastic02.wav")
Schema.voices.Add("CitizenFemale", "get the hell out", "GET THE HELL OUT OF HERE!", "vo/npc/female01/gethellout.wav")
Schema.voices.Add("CitizenFemale", "good god", "Good god!", "vo/npc/female01/goodgod.wav")
Schema.voices.Add("CitizenFemale", "oh god", "Oh god!", "vo/npc/female01/gordead_ans04.wav")
Schema.voices.Add("CitizenFemale", "hes dead", "He's dead.", "vo/npc/female01/gordead_ques01.wav")
Schema.voices.Add("CitizenFemale", "look hes dead", "Look! He's dead!", "vo/npc/female01/gordead_ques07.wav")
Schema.voices.Add("CitizenFemale", "he's dead", "He's dead.", "vo/npc/female01/gordead_ques01.wav")
Schema.voices.Add("CitizenFemale", "look he's dead", "Look! He's dead!", "vo/npc/female01/gordead_ques07.wav")
Schema.voices.Add("CitizenFemale", "got one", "Got one!", "vo/npc/female01/gotone01.wav")
Schema.voices.Add("CitizenFemale", "got one2", "Haha! I got one!", "vo/npc/female01/gotone02.wav")
Schema.voices.Add("CitizenFemale", "hacks", "HACKS!", "vo/npc/female01/hacks01.wav")
Schema.voices.Add("CitizenFemale", "headcrabs", "Headcrabs!", "vo/npc/female01/headcrabs01.wav")
Schema.voices.Add("CitizenFemale", "headcrabs2", "Headcrabs!", "vo/npc/female01/headcrabs02.wav")
Schema.voices.Add("CitizenFemale", "medkit", "Take this medkit.", "vo/npc/female01/health01.wav")
Schema.voices.Add("CitizenFemale", "medkit2", "Take this medkit!", "vo/npc/female01/health03.wav")
Schema.voices.Add("CitizenFemale", "help", "Help!", "vo/npc/female01/help01.wav")
Schema.voices.Add("CitizenFemale", "ill stay here", "I'll stay here.", "vo/npc/female01/illstayhere01.wav")
Schema.voices.Add("CitizenFemale", "i'll stay here", "I'll stay here.", "vo/npc/female01/illstayhere01.wav")
Schema.voices.Add("CitizenFemale", "all over", "That's you all over.", "vo/npc/female01/answer01.wav")
Schema.voices.Add("CitizenFemale", "figures", "Figures.", "vo/npc/female01/answer03.wav")
Schema.voices.Add("CitizenFemale", "dwell on it", "Try not to dwell on it.", "vo/npc/female01/answer04.wav")
Schema.voices.Add("CitizenFemale", "talk later", "Can we talk about this later?.", "vo/npc/female01/answer05.wav")
Schema.voices.Add("CitizenFemale", "same here", "Same here.", "vo/npc/female01/answer07.wav")
Schema.voices.Add("CitizenFemale", "know what you mean", "Know what you mean.", "vo/npc/female01/answer08.wav")
Schema.voices.Add("CitizenFemale", "talking to yourself", "You\'re talking to yourself again.", "vo/npc/female01/answer09.wav")
Schema.voices.Add("CitizenFemale", "too loud", "I wouldn't say that too loud.", "vo/npc/female01/answer10.wav")
Schema.voices.Add("CitizenFemale", "tombstone", "Yeah, I'll put it on your tombstone.", "vo/npc/female01/answer03.wav")
Schema.voices.Add("CitizenFemale", "with you", "Yeah, I'm with you.", "vo/npc/female01/answer13.wav")
Schema.voices.Add("CitizenFemale", "one way of looking at it", "That's one way of looking at it.", "vo/npc/female01/answer15.wav")
Schema.voices.Add("CitizenFemale", "you and me", "Yeah, you and me both.", "vo/npc/female01/answer14.wav")
Schema.voices.Add("CitizenFemale", "original thought", "Have you ever had an original thought?", "vo/npc/female01/answer16.wav")
Schema.voices.Add("CitizenFemale", "shut up", "I'm not even gonna tell you to shut up.", "vo/npc/female01/answer17.wav")
Schema.voices.Add("CitizenFemale", "concentrate", "Let's concentrate on the task at hand.", "vo/npc/female01/answer18.wav")
Schema.voices.Add("CitizenFemale", "on your work", "Keep your mind on your work!", "vo/npc/female01/answer19.wav")
Schema.voices.Add("CitizenFemale", "mind in the gutter", "Tch, your mind is in the gutter.", "vo/npc/female01/answer20.wav")
Schema.voices.Add("CitizenFemale", "don't be sure", "Don't be so sure of that.", "vo/npc/female01/answer21.wav")
Schema.voices.Add("CitizenFemale", "you never know", "You never know.", "vo/npc/female01/answer22.wav")
Schema.voices.Add("CitizenFemale", "never can tell", "Never can tell.", "vo/npc/female01/answer23.wav")
Schema.voices.Add("CitizenFemale", "telling me", "Why are you telling me?", "vo/npc/female01/answer24.wav")
Schema.voices.Add("CitizenFemale", "how bout that", "How 'bout that?", "vo/npc/female01/answer25.wav")
Schema.voices.Add("CitizenFemale", "too much information", "That's... more information than I require.", "vo/npc/female01/answer26.wav")
Schema.voices.Add("CitizenFemale", "bet", "Wanna bet?", "vo/npc/female01/answer27.wav")
Schema.voices.Add("CitizenFemale", "had a dime", "I wish I had a dime for every time somebody said that.", "vo/npc/female01/answer28.wav")
Schema.voices.Add("CitizenFemale", "supposed to do", "What am I supposed to do about it?", "vo/npc/female01/answer29.wav")
Schema.voices.Add("CitizenFemale", "talking to me", "You talking to me?", "vo/npc/female01/answer30.wav")
Schema.voices.Add("CitizenFemale", "nip that talk", "You should nip that talk in the bud.", "vo/npc/female01/answer31.wav")
Schema.voices.Add("CitizenFemale", "right on", "Right on!", "vo/npc/female01/answer32.wav")
Schema.voices.Add("CitizenFemale", "no argument", "No argument there.", "vo/npc/female01/answer33.wav")
Schema.voices.Add("CitizenFemale", "hawaii", "Don't forget Hawaii.", "vo/npc/female01/answer34.wav")
Schema.voices.Add("CitizenFemale", "can't remember", "I can't remember the last time I had... uh, well- anything.", "vo/npc/female01/answer35.wav")
Schema.voices.Add("CitizenFemale", "get to you", "Try not to let it get to you.", "vo/npc/female01/answer36.wav")
Schema.voices.Add("CitizenFemale", "wouldn't be the first time", "Wouldn't be the first time.", "vo/npc/female01/answer37.wav")
Schema.voices.Add("CitizenFemale", "sure about that", "You sure about that?", "vo/npc/female01/answer38.wav")
Schema.voices.Add("CitizenFemale", "leave it alone", "Leave it alone!", "vo/npc/female01/answer39.wav")
Schema.voices.Add("CitizenFemale", "enough out of you", "Yeah, that's enough out of you.", "vo/npc/female01/answer40.wav")
Schema.voices.Add("CitizenFemale", "behind you1", "Behind you!", "vo/npc/female01/behindyou01.wav")
Schema.voices.Add("CitizenFemale", "behind you2", "Behind you!", "vo/npc/female01/behindyou02.wav")
Schema.voices.Add("CitizenFemale", "busy", "Can't you see I'm busy?", "vo/npc/female01/busy02.wav")
Schema.voices.Add("CitizenFemale", "look out below", "Look out below!", "vo/npc/female01/cit_dropper04.wav")
Schema.voices.Add("CitizenFemale", "civil protection", "Civil Protection!", "vo/npc/female01/civilprotection01.wav")
Schema.voices.Add("CitizenFemale", "civil protection2", "Civil Protection!.", "vo/npc/female01/civilprotection02.wav")
Schema.voices.Add("CitizenFemale", "combine", "Combine!", "vo/npc/female01/combine01.wav")
Schema.voices.Add("CitizenFemale", "combine2", "Combine!", "vo/npc/female01/combine02.wav")
Schema.voices.Add("CitizenFemale", "cover me", "Cover me while I reload!", "vo/npc/female01/coverwhilereload01.wav")
Schema.voices.Add("CitizenFemale", "cover me2", "Cover me while I reload!", "vo/npc/female01/coverwhilereload02.wav")
Schema.voices.Add("CitizenFemale", "cps", "CPs!", "vo/npc/female01/cps01.wav")
Schema.voices.Add("CitizenFemale", "cps2", "CPs!", "vo/npc/female01/cps02.wav")
Schema.voices.Add("CitizenFemale", "doing something", "Should we be doing something?", "vo/npc/female01/doingsomething.wav")
Schema.voices.Add("CitizenFemale", "excuse me", "Excuse me.", "vo/npc/female01/excuseme01.wav")
Schema.voices.Add("CitizenFemale", "excuse me2", "Excuse me.", "vo/npc/female01/excuseme02.wav")
Schema.voices.Add("CitizenFemale", "fantastic", "Fantastic.", "vo/npc/female01/fantastic01.wav")
Schema.voices.Add("CitizenFemale", "fantastic2", "Fantastic.", "vo/npc/female01/fantastic02.wav")
Schema.voices.Add("CitizenFemale", "finally", "Finally!", "vo/npc/female01/finally.wav")
Schema.voices.Add("CitizenFemale", "get down", "Get down!", "vo/npc/female01/getdown02.wav")
Schema.voices.Add("CitizenFemale", "get going soon", "Are we going to get going soon?", "vo/npc/female01/getgoingsoon.wav")
Schema.voices.Add("CitizenFemale", "get out", "Get the hell out of here!", "vo/npc/female01/gethellout.wav")
Schema.voices.Add("CitizenFemale", "good god", "Good god!", "vo/npc/female01/goodgod.wav")
Schema.voices.Add("CitizenFemale", "now what", "Now what?", "vo/npc/female01/gordead_ans01.wav")
Schema.voices.Add("CitizenFemale", "going so well", "And things were going so well.", "vo/npc/female01/gordead_ans02.wav")
Schema.voices.Add("CitizenFemale", "don't tell me", "Don't tell me...", "vo/npc/female01/gordead_ans03.wav")
Schema.voices.Add("CitizenFemale", "oh god", "Oh god.", "vo/npc/female01/gordead_ans04.wav")
Schema.voices.Add("CitizenFemale", "oh no", "Oh no!", "vo/npc/female01/gordead_ans05.wav")
Schema.voices.Add("CitizenFemale", "please no", "Please no!", "vo/npc/female01/gordead_ans06.wav")
Schema.voices.Add("CitizenFemale", "if you dare say", "If you dare say, \"that's gotta hurt,\", I'll kill you.", "vo/npc/female01/gordead_ans07.wav")
Schema.voices.Add("CitizenFemale", "bury him here", "Should we bury him here?", "vo/npc/female01/gordead_ans08.wav")
Schema.voices.Add("CitizenFemale", "spread the word", "Spread the word.", "vo/npc/female01/gordead_ans10.wav")
Schema.voices.Add("CitizenFemale", "had a feeling", "I had a feeling even he couldn't help us.", "vo/npc/female01/gordead_ans09.wav")
Schema.voices.Add("CitizenFemale", "what's the use", "What's the use?", "vo/npc/female01/gordead_ans11.wav")
Schema.voices.Add("CitizenFemale", "what's the point", "What's the point?", "vo/npc/female01/gordead_ans12.wav")
Schema.voices.Add("CitizenFemale", "why go on", "Why go on?", "vo/npc/female01/gordead_ans13.wav")
Schema.voices.Add("CitizenFemale", "we're done for", "We're done for.", "vo/npc/female01/gordead_ans14.wav")
Schema.voices.Add("CitizenFemale", "now what", "Well... now what?", "vo/npc/female01/gordead_ans15.wav")
Schema.voices.Add("CitizenFemale", "dibs", "Dibs on the suit!", "vo/npc/female01/gordead_ans16.wav")
Schema.voices.Add("CitizenFemale", "done this before", "He's done this before; He'll be okay!", "vo/npc/female01/gordead_ans18.wav")
Schema.voices.Add("CitizenFemale", "gonna be sick", "I'm gonna be sick.", "vo/npc/female01/gordead_ans19.wav")
Schema.voices.Add("CitizenFemale", "take his crowbar", "Somebody take his crowbar!", "vo/npc/female01/gordead_ans20.wav")
Schema.voices.Add("CitizenFemale", "he's dead", "He's dead!", "vo/npc/female01/gordead_ques01.wav")
Schema.voices.Add("CitizenFemale", "what a way", "What a way to go!", "vo/npc/female01/gordead_ques02.wav")
Schema.voices.Add("CitizenFemale", "this can't be", "This can't be!", "vo/npc/female01/gordead_ques06.wav")
Schema.voices.Add("CitizenFemale", "he's dead2", "Look, he's dead!", "vo/npc/female01/gordead_ques07.wav")
Schema.voices.Add("CitizenFemale", "this is bad", "This is bad.", "vo/npc/female01/gordead_ques10.wav")
Schema.voices.Add("CitizenFemale", "not supposed to end like this", "It's not supposed to end like this!", "vo/npc/female01/gordead_ques14.wav")
Schema.voices.Add("CitizenFemale", "what now", "What now?", "vo/npc/female01/gordead_ques16.wav")
Schema.voices.Add("CitizenFemale", "got one", "Got one!", "vo/npc/female01/gotone01.wav")
Schema.voices.Add("CitizenFemale", "got one2", "Got one!", "vo/npc/female01/gotone02.wav")
Schema.voices.Add("CitizenFemale", "reloading", "Gotta reload!", "vo/npc/female01/gottareload01.wav")
Schema.voices.Add("CitizenFemale", "gunship", "Gunship!", "vo/npc/female01/gunship02.wav")
Schema.voices.Add("CitizenFemale", "hacks", "Hacks!", "vo/npc/female01/hacks01.wav")
Schema.voices.Add("CitizenFemale", "hacks2", "Hacks!", "vo/npc/female01/hacks02.wav")
Schema.voices.Add("CitizenFemale", "heads up", "Heads up!", "vo/npc/female01/headsup01.wav")
Schema.voices.Add("CitizenFemale", "heads up", "Heads up!", "vo/npc/female01/headsup02.wav")
Schema.voices.Add("CitizenFemale", "help", "Help!", "vo/npc/female01/help01.wav")
Schema.voices.Add("CitizenFemale", "here come hacks", "Here come the hacks!", "vo/npc/female01/herecomehacks01.wav")
Schema.voices.Add("CitizenFemale", "here come hacks2", "Here come the hacks!", "vo/npc/female01/herecomehacks02.wav")
Schema.voices.Add("CitizenFemale", "here they come", "Here they come!", "vo/npc/female01/heretheycome01.wav")
Schema.voices.Add("CitizenFemale", "here to help", "We thought you were here to help.", "vo/npc/female01/heretohelp01.wav")
Schema.voices.Add("CitizenFemale", "here to help2", "We thought you were here to help!", "vo/npc/female01/heretohelp02.wav")
Schema.voices.Add("CitizenFemale", "hi", "Hi.", "vo/npc/female01/hi01.wav")
Schema.voices.Add("CitizenFemale", "hi2", "Hi.", "vo/npc/female01/hi02.wav")
Schema.voices.Add("CitizenFemale", "hey doc", "Hey doc.", "vo/npc/female01/heydoc01.wav")
Schema.voices.Add("CitizenFemale", "hey doc", "Hey doc.", "vo/npc/female01/heydoc02.wav")
Schema.voices.Add("CitizenFemale", "hit in the gut", "Ugh..! Hit in the gut...", "vo/npc/female01/hitingut01.wav")
Schema.voices.Add("CitizenFemale", "hit in the gut", "Ugh..! Hit in the gut...", "vo/npc/female01/hitingut02.wav")
Schema.voices.Add("CitizenFemale", "hold down this spot", "I'll stay here and hold down this spot.", "vo/npc/female01/holddownspot01.wav")
Schema.voices.Add("CitizenFemale", "hold down this spot", "I'll stay here and hold down this spot.", "vo/npc/female01/holddownspot02.wav")
Schema.voices.Add("CitizenFemale", "i'll stay here", "I'll stay here.", "vo/npc/female01/illstayhere01.wav")
Schema.voices.Add("CitizenFemale", "i'm hurt", "I'm hurt!", "vo/npc/female01/imhurt01.wav")
Schema.voices.Add("CitizenFemale", "i'm hurt2", "I'm hurt!", "vo/npc/female01/imhurt02.wav")
Schema.voices.Add("CitizenFemale", "i'm sticking here", "I'm sticking here.", "vo/npc/female01/imstickinghere01.wav")
Schema.voices.Add("CitizenFemale", "incoming", "Incoming!", "vo/npc/female01/incoming02.wav")
Schema.voices.Add("CitizenFemale", "it's a manhack", "It's a manhack!", "vo/npc/female01/itsamanhack01.wav")
Schema.voices.Add("CitizenFemale", "it's a manhack2", "It's a manhack!", "vo/npc/female01/itsamanhack02.wav")
Schema.voices.Add("CitizenFemale", "lead the way", "You lead the way.", "vo/npc/female01/leadtheway01.wav")
Schema.voices.Add("CitizenFemale", "lead the way2", "You lead the way!", "vo/npc/female01/leadtheway02.wav")
Schema.voices.Add("CitizenFemale", "like that", "Like that?", "vo/npc/female01/likethat.wav")
Schema.voices.Add("CitizenFemale", "let's go", "Let's go.", "vo/npc/female01/letsgo01.wav")
Schema.voices.Add("CitizenFemale", "let's go2", "Let's go!", "vo/npc/female01/letsgo02.wav")
Schema.voices.Add("CitizenFemale", "little corner", "I've got my little corner and I'm sticking to it.", "vo/npc/female01/littlecorner01.wav")
Schema.voices.Add("CitizenFemale", "moan", "*moans*", "vo/npc/female01/moan01.wav")
Schema.voices.Add("CitizenFemale", "moan2", "*moans*", "vo/npc/female01/moan02.wav")
Schema.voices.Add("CitizenFemale", "moan3", "*moans*", "vo/npc/female01/moan03.wav")
Schema.voices.Add("CitizenFemale", "moan4", "*moans*", "vo/npc/female01/moan04.wav")
Schema.voices.Add("CitizenFemale", "moan5", "*moans*", "vo/npc/female01/moan05.wav")
Schema.voices.Add("CitizenFemale", "my arm", "Ooh, my arm!", "vo/npc/female01/myarm01.wav")
Schema.voices.Add("CitizenFemale", "my arm2", "My arm!", "vo/npc/female01/myarm02.wav")
Schema.voices.Add("CitizenFemale", "my gut", "Hoo.. ooh, my gut!", "vo/npc/female01/mygut02.wav")
Schema.voices.Add("CitizenFemale", "my leg", "My leg!", "vo/npc/female01/myleg01.wav")
Schema.voices.Add("CitizenFemale", "my leg2", "Ah, my leg!", "vo/npc/female01/myleg02.wav")
Schema.voices.Add("CitizenFemale", "nice", "Nice.", "vo/npc/female01/nice01.wav")
Schema.voices.Add("CitizenFemale", "nice2", "Nice!", "vo/npc/female01/nice02.wav")
Schema.voices.Add("CitizenFemale", "no", "No.", "vo/npc/female01/no01.wav")
Schema.voices.Add("CitizenFemale", "no2", "No!", "vo/npc/female01/no02.wav")
Schema.voices.Add("CitizenFemale", "oh no2", "Oh no!", "vo/npc/female01/ohno.wav")
Schema.voices.Add("CitizenFemale", "okay", "Okay.", "vo/npc/female01/ok01.wav")
Schema.voices.Add("CitizenFemale", "okay2", "Okay!", "vo/npc/female01/ok02.wav")
Schema.voices.Add("CitizenFemale", "cps", "CPs!", "vo/npc/female01/cps01.wav")

Schema.voices.Add("Overwatch", "ch1", "Overwatch, activation central transport stabilization teams.", "npc/combine_soldier/vo/prison_soldier_activatecentral.wav")
Schema.voices.Add("Overwatch", "ch2", "Overwatch confirms double boomers dispatched inbound, ghost drop inbound, prepare for skyshield heavy suppression and wrapup.", "npc/combine_soldier/vo/prison_soldier_boomersinbound.wav")
Schema.voices.Add("Overwatch", "ch3", "Hardpoint Nomad, reactivate perimeter restrictors and report. Hardpoint Nomad, reactivate your perimeter restrictors and report. Nomad, get those restrictors back on line, your sector shows active biotics.", "npc/combine_soldier/vo/prison_soldier_bunker1.wav")
Schema.voices.Add("Overwatch", "ch4", "Hardpoint Shadow, report blackout status. Hardpoint Shadow, report blackout status. Hardpoint 139 is oneway. Hunter 6, detach, sweep and confirm.", "npc/combine_soldier/vo/prison_soldier_bunker2.wav")
Schema.voices.Add("Overwatch", "ch5", "Leader 9 to Hardpoint Stinger report containment status. Post Stinger, do you read? Team 4, team 9 assemble and reinforce, leader 9 closing for local control.", "npc/combine_soldier/vo/prison_soldier_bunker3.wav")
Schema.voices.Add("Overwatch", "ch6", "Primary has moved to a containment zone. All remaining teams dispatch to Delta 8. We got him now.", "npc/combine_soldier/vo/prison_soldier_containd8.wav")
Schema.voices.Add("Overwatch", "ch7", "Fall back and reinforce sector Black 4, Overwatch requests skyshield sector reinforcement. Drop is inbound.", "npc/combine_soldier/vo/prison_soldier_fallback_b4.wav")
Schema.voices.Add("Overwatch", "ch8", "Warning, primary target is, uhh, engaged in, uhh command and control tactics with biotics. Repeat, primary target has tactical C&C of biotics.", "npc/combine_soldier/vo/prison_soldier_freeman_antlions.wav")
Schema.voices.Add("Overwatch", "ch9", "Central transport facility, Nova Prospekt contact blackout, full biotic overrun.", "npc/combine_soldier/vo/prison_soldier_fullbioticoverrun.wav")
Schema.voices.Add("Overwatch", "ch10", "Leader 9 deserviced, Judge 3 field promotion active.", "npc/combine_soldier/vo/prison_soldier_leader9dead.wav")
Schema.voices.Add("Overwatch", "ch11", "Uh, negative, no sector containment, no confirmation on target one vector. We have secondary perimeter overruns, what is ETA on skyshield drop?", "npc/combine_soldier/vo/prison_soldier_negativecontainment.wav")
Schema.voices.Add("Overwatch", "ch12", "Drop Reinforcement teams deploy and prosecute sector Delta 7, contact confirmed with primary target. Target is non-mobile, hunters, scan for possible accomplice.", "npc/combine_soldier/vo/prison_soldier_prosecuted7.wav")
Schema.voices.Add("Overwatch", "ch13", "Team Sundown 3 deserviced, Helix 2 go active and intercept, Leader 12 out.", "npc/combine_soldier/vo/prison_soldier_sundown3dead.wav")
Schema.voices.Add("Overwatch", "ch14", "All perimeter units, displace to internal highpoints and prepare for final prosecution.", "npc/combine_soldier/vo/prison_soldier_tohighpoints.wav")
Schema.voices.Add("Overwatch", "ch15", "Team Sundown 3, set viscerators in sector Apex 5, and advance for contact. We have biotics in the perimeter.", "npc/combine_soldier/vo/prison_soldier_visceratorsa5.wav")
Schema.voices.Add("Overwatch", "grenade", "Grenade!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("Overwatch", "bouncerbouncer", "Bouncer! Bouncer!", "npc/combine_soldier/vo/bouncerbouncer.wav")
Schema.voices.Add("Overwatch", "ripcordripcord", "Ripcord! Ripcord!", "npc/combine_soldier/vo/ripcordripcord.wav")
Schema.voices.Add("Overwatch", 'one down', "One down!", "npc/combine_soldier/vo/onedown.wav")
Schema.voices.Add("Overwatch", 'flaredown', "Flare down!", "npc/combine_soldier/vo/flaredown.wav")
Schema.voices.Add("Overwatch", "possible hostiles", "Ready weapons. Possible hostiles inbound.", "npc/combine_soldier/vo/readyweaponshostilesinbound.wav")
Schema.voices.Add("Overwatch", "clear", "Reporting clear.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("Overwatch", "sightline", "Sightline is clear.", "npc/combine_soldier/vo/sightlineisclear.wav")
Schema.voices.Add("Overwatch", "holding in position", "Stabilization team holding in position.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("Overwatch", "report sightlines", "Stay alert. Report sightlines.", "npc/combine_soldier/vo/stayalertreportsightlines.wav")
Schema.voices.Add("Overwatch", "visual exogen", "Visual on exogen.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("Overwatch", "prep contact", "Weapons off safe. Prep for contact.", "npc/combine_soldier/vo/weaponsoffsafeprepforcontact.wav")
Schema.voices.Add("Overwatch", "anti1", "Anti-citizen one.", "npc/combine_soldier/vo/anticitizenone.wav")
Schema.voices.Add("Overwatch", "affirm2", "Affirmative.", "npc/combine_soldier/vo/affirmative.wav")
Schema.voices.Add("Overwatch", "affirm3", "Affirmative.", "npc/combine_soldier/vo/affirmative2.wav")
Schema.voices.Add("Overwatch", "need help", "Need any help with this one?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("Overwatch", "non patrol", "Non-patrol region.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("Overwatch", "outlands", "Outlands zone.", "npc/metropolice/vo/outlandzone.wav")